# Generated by Django 6.0 on 2026-01-05 05:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_break_time', models.DurationField(default=datetime.timedelta)),
                ('total_work_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('INCOMPLETE', 'Incomplete'), ('ABSENT', 'Absent')], default='INCOMPLETE', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendance__user_id_c01e0c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
