# Generated by Django 6.0 on 2026-01-05 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_break_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
